function sonics = import_sonics(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   SONICS = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   SONICS = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2022/08/25 14:50:58

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 5;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = [dataArray{:,1:end-1}];
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[2,4,5,6,8,9,10,12,13,14,16,17,18]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [2,4,5,6,8,9,10,12,13,14,16,17,18]);
rawCellColumns = raw(:, [1,3,7,11,15]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
sonics = dataset;
sonics.Time = rawCellColumns(:, 1);
sonics.record = cell2mat(rawNumericColumns(:, 1));
sonics.id115 = rawCellColumns(:, 2);
sonics.u115 = cell2mat(rawNumericColumns(:, 2));
sonics.v115 = cell2mat(rawNumericColumns(:, 3));
sonics.w115 = cell2mat(rawNumericColumns(:, 4));
sonics.unit115 = rawCellColumns(:, 3);
sonics.Vsound115 = cell2mat(rawNumericColumns(:, 5));
sonics.T115 = cell2mat(rawNumericColumns(:, 6));
sonics.stat115 = cell2mat(rawNumericColumns(:, 7));
sonics.id55 = rawCellColumns(:, 4);
sonics.u55 = cell2mat(rawNumericColumns(:, 8));
sonics.v55 = cell2mat(rawNumericColumns(:, 9));
sonics.w55 = cell2mat(rawNumericColumns(:, 10));
sonics.unit55 = rawCellColumns(:, 5);
sonics.Vsound55 = cell2mat(rawNumericColumns(:, 11));
sonics.T55 = cell2mat(rawNumericColumns(:, 12));
sonics.stat55 = cell2mat(rawNumericColumns(:, 13));
